"""Backend contract shared by real and MuJoCo controllers."""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import Protocol, runtime_checkable


@runtime_checkable
class ControllerProtocol(Protocol):
    def set_mode(self, motor_id: int, mode: int) -> None: ...
    def set_all_mode(self, mode: int) -> None: ...
    def get_mode(self, motor_id: int) -> int | None: ...
    def set_speed(self, motor_id: int, speed: int) -> None: ...
    def set_speeds(self, speeds: Mapping[int, int]) -> None: ...
    def set_all_speed(self, speed: int) -> None: ...
    def set_velocity(self, motor_id: int, velocity: int) -> None: ...
    def set_velocities(self, velocities: Mapping[int, int]) -> None: ...
    def set_acceleration(self, motor_id: int, acceleration: int) -> None: ...
    def set_accelerations(self, accelerations: Mapping[int, int]) -> None: ...
    def set_torque(self, motor_id: int, torque: int) -> None: ...
    def set_torques(self, motor_ids: Iterable[int], torque: int) -> None: ...
    def enable_torque(self) -> None: ...
    def disable_torque(self) -> None: ...
    def set_position(self, motor_id: int, position: float) -> None: ...
    def set_positions(self, positions: Mapping[int, float]) -> None: ...
    def set_raw_position(self, motor_id: int, position: int) -> None: ...
    def set_raw_positions(self, positions: Mapping[int, int]) -> None: ...
    def get_position(self, motor_id: int) -> int: ...
    def close(self) -> None: ...


__all__ = ["ControllerProtocol"]
